model_name: BertEncoderDecoder

encoder:
  model_name: Bert
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  hidden_act: 'gelu'
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 512
  type_vocab_size: 2
  initializer_range: 0.02
  layer_norm_eps: 0.000000000001
  position_embedding_type: 'absolute' # absolute, relative_key, relative_key_query
  use_cache: True
  classifier_dropout: null
  do_sample: False
  num_beams: 1

decoder:
  model_name: Bert
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  hidden_act: 'gelu'
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 512
  type_vocab_size: 2
  initializer_range: 0.02
  layer_norm_eps: 0.000000000001
  position_embedding_type: 'absolute' # absolute, relative_key, relative_key_query
  use_cache: True
  classifier_dropout: null
  do_sample: False
  num_beams: 1