symbol: copy
commutative: False
reverse_output: False
eos: True
padding: True
pad_token: '0'
max_position: 15

train:
  dataset_cls: MineSweeperGeneratorDatasetWithCoupledPositions
  min_n_len: 6
  max_n_len: 10
  min_mine_ratio: 0.1
  max_mine_ratio: 0.25
  n_data: 100000
  randomize: True


val:
  dataset_cls: MineSweeperGeneratorDatasetWithCoupledPositions
  min_n_len: 10
  max_n_len: 10
  min_mine_ratio: 0.1
  max_mine_ratio: 0.25
  n_data: 10000
  randomize: False
  

val_long:
  dataset_cls: MineSweeperGeneratorDatasetWithCoupledPositions
  min_n_len: 12
  max_n_len: 12
  min_mine_ratio: 0.1
  max_mine_ratio: 0.25
  n_data: 10000
  randomize: False
