symbol: +
reverse_input: True
reverse_output: True
reverse_output_order: False
padding: False
pad_token: '0'

vocab: 0 1 2 3 4 5 6 7 8 9 + > =
eos: True
bos_to_eos: True

train:
  dataset_cls: MultipleAdditionScratchPadDataset
  min_n_digits: 1
  max_n_digits: 10
  min_n_operands: 2
  max_n_operands: 5
  n_data: 1000000

val:
  dataset_cls: MultipleAdditionScratchPadDataset
  min_n_digits: 1
  max_n_digits: 10
  min_n_operands: 2
  max_n_operands: 5
  n_data: 10000

val_many_digits:
  dataset_cls: MultipleAdditionScratchPadDataset
  min_n_digits: 1
  max_n_digits: 10
  min_n_operands: 6
  max_n_operands: 7
  n_data: 10000

val_many_operands:
  dataset_cls: MultipleAdditionScratchPadDataset
  min_n_digits: 11
  max_n_digits: 15
  min_n_operands: 2
  max_n_operands: 5
  n_data: 10000

val_long:
  dataset_cls: MultipleAdditionScratchPadDataset
  min_n_digits: 11
  max_n_digits: 20
  min_n_operands: 6
  max_n_operands: 7
  n_data: 10000
