symbol: '*'
reverse_input: False
reverse_output: True
padding: True
pad_token: '0'
max_position_digits: 20
max_position_operands: 10

vocab: 0 1 2 3 4 5 6 7 8 9 * + > =
eos: True
bos_to_eos: True

train:
  dataset_cls: MultiplicationScratchPadDatasetWithCoupledPositions
  min_n_digits_1: 1
  max_n_digits_1: 10
  min_n_digits_2: 1
  max_n_digits_2: 4
  n_data: 1000000
  randomize: True

val:
  dataset_cls: MultiplicationScratchPadDatasetWithCoupledPositions
  min_n_digits_1: 1
  max_n_digits_1: 10
  min_n_digits_2: 1
  max_n_digits_2: 4
  n_data: 10000
  randomize: False

val_long_first:
  dataset_cls: MultiplicationScratchPadDatasetWithCoupledPositions
  min_n_digits_1: 1
  max_n_digits_1: 10
  min_n_digits_2: 5
  max_n_digits_2: 6
  n_data: 10000
  randomize: False

val_long_second:
  dataset_cls: MultiplicationScratchPadDatasetWithCoupledPositions
  min_n_digits_1: 11
  max_n_digits_1: 15
  min_n_digits_2: 1
  max_n_digits_2: 4
  n_data: 10000
  randomize: False

val_long:
  dataset_cls: MultiplicationScratchPadDatasetWithCoupledPositions
  min_n_digits_1: 11
  max_n_digits_1: 15
  min_n_digits_2: 5
  max_n_digits_2: 6
  n_data: 10000
  randomize: False
