symbol: '*'
commutative: False
reverse_output: True
eos: True
bos_to_eos: True
padding: True
pad_token: '0'
M: 1

train:
  dataset_cls: NxMMultiplicationDataset
  min_n_digits: 1
  max_n_digits: 5
  n_data: 100000

val:
  dataset_cls: NxMMultiplicationDataset
  min_n_digits: 5
  max_n_digits: 5
  n_data: 10000

val_long:
  dataset_cls: NxMMultiplicationDataset
  min_n_digits: 10
  max_n_digits: 10
  n_data: 10000
